add new commands
prooph/micro pull request #17
Opened 2017-01-23 12:12 UTC by prolic

2017-01-23 12:36 UTC, oqq reviewed
Instead of using comments in docker-compose.yml and read them with a regular expression, we should use docker labels to define `gateway` and `server` and read/write that values with symphony yaml component. Should be less error prone I guess.

2017-01-23 13:18 UTC, bweston92 commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
Maybe we should keep consistent with other PHP functionality?
Where-by directories return without `/`.
Take a look at `dirname` and `__DIR__`

2017-01-23 14:27 UTC, oqq commented on src/Command/CreateMySqlCommand.php
> +                        "$dbPort:3306",
Publishing a port to host should be optional.

2017-01-23 14:27 UTC, oqq commented on src/Command/CreatePostgresCommand.php
> +                        "$dbPort:5432",
Publishing a port to host should be optional.

2017-01-23 14:27 UTC, oqq commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
The root dir for a php process is always `pwd`. So this method could be removed.
If the user wants to provide another dir, a cli option should be used.
Maybe the user should get informed where the docker-compose.yml file would be stored before executed.

2017-01-23 14:42 UTC, prolic commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
The php process directory is not important here. We need to real project root dir.

2017-01-23 14:43 UTC, prolic commented on src/Command/CreateMySqlCommand.php
> +                        "$dbPort:3306",
Doesn't hurt and helps modifying later, if needed. We should always assume the end-user has no knowledge about docker.

2017-01-23 14:45 UTC, oqq commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
We need the location for the docker-compose.yml file, or the project root dir? Why is the project root dir important?

2017-01-23 14:46 UTC, bweston92 commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
I'm not saying it isn't important I'm saying it isn't consistent with other PHP apis.

2017-01-23 14:53 UTC, prolic commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
location of docker-compose.yml (which is in project root dir most times).

2017-01-23 14:55 UTC, bweston92 commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
But instead of returning `/usr/src/app/` return `/usr/src/app` same as `SplFileInfo::getPath()` etc

2017-01-23 14:57 UTC, oqq commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
So how is the users process?
```bash
$ bin/micro micro:create:php-image
$ docker-compose up -d
```

This should work without knowledge of the project root, right?

2017-01-23 15:24 UTC, prolic commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
@bweston92 ok about the trailing slash, I remote it!

2017-01-23 15:25 UTC, prolic commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
@oqq yes. but you could do something like this:

```
cd bin
./micro micro:create:php-image
```

so pwd is different, but I still need to get to project root.

2017-01-23 15:30 UTC, oqq commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
so.. than I would prefer `chdir(dirname(__DIR__));` in bin/micro.php instead of searching throw directories.

2017-01-23 16:24 UTC, prolic commented on src/Command/CreatePostgresCommand.php
> +                        "$dbPort:5432",
updated.

2017-01-23 16:26 UTC, prolic commented on src/Command/AbstractCommand.php
> +    protected function getRootDir(): string
it can be in vendor directory :)

2017-01-23 22:17 UTC, sandrokeil commented
@prolic We can try to use [madkom/nginx-configurator](https://github.com/madkom/nginx-configurator) to generate configs [like this](https://github.com/sandrokeil/micro-do/blob/eb19dc7eaaec86847d5f695e8fa76f0b235edcc7/gateway/sites-enabled/www.conf). Looks like edit is supported. /cc @oqq

2017-01-24 14:28 UTC, prolic commented
@sandrokeil thanks for the hint with `madkom/nginx-configurator` - works great!
@oqq I updated this PR

Thanks at all!

2017-01-24 14:31 UTC, prolic commented
oh before I forgot: I hardcoded the `service` and `gateway` directory. Making this configurable is not needed and complicates things for now.

2017-01-24 14:32 UTC, prolic commented
Damn, due to changes the `SetupCommandTest` is not running any more - @oqq wanna pick this, too?

2017-01-24 17:41 UTC, codeliner requested changes

2017-01-24 17:41 UTC, codeliner commented on gateway/README.md
> +# Gateway directory
Question: should we move cli + structure into a skeleton?
Reason: You clone the skeleton ones and modify it to your needs, but you may wish to update micro as a library like any other composer dependency.

2017-01-24 18:40 UTC, prolic commented
Ok. Let's create an issue and do this after new commands pr is merged.

Am 25.01.2017 01:41 schrieb "Alexander Miertsch" <notifications@github.com>:

> *@codeliner* requested changes on this pull request.
> ------------------------------
>
> In gateway/README.md
> <https://github.com/prooph/micro/pull/17#pullrequestreview-18206401>:
>
> > @@ -0,0 +1,5 @@
> +# Gateway directory
>
> Question: should we move cli + structure into a skeleton?
> Reason: You clone the skeleton ones and modify it to your needs, but you
> may wish to update micro as a library like any other composer dependency.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/prooph/micro/pull/17#pullrequestreview-18206401>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAYEvN94kXODiwsoPByOFS2Wv_eqvDOfks5rVje3gaJpZM4Lq-No>
> .
>

2017-01-24 18:59 UTC, codeliner commented
issue created: https://github.com/prooph/micro/issues/25

2017-01-24 18:59 UTC, codeliner approved these changes

2017-01-24 19:00 UTC, codeliner commented
if tests are green, PR can be merged

2017-01-24 19:18 UTC, merged